# Tensor创建方法

## 直接创建Tensor

In [2]:
import torch
import numpy as np

In [3]:
## torch.tensor()
## torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False)
        # data: 数据，可以是 list，numpy
        # dtype: 数据类型，默认与 data 的一致
        # device: 所在设备，cuda/cpu
        # requires_grad: 是否需要梯度
        # pin_memory: 是否存于锁页内存
# 其中数据类型既可以是numpy格式，也可以是list格式

In [4]:
# numpy格式
arr = np.ones((3, 3))
# 创建存放在 GPU 的数据
# t = torch.tensor(arr, device='cuda')
t= torch.tensor(arr)
print(t)
# 列表格式
x = torch.tensor([1,2,3,4])
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


tensor([1, 2, 3, 4])

In [22]:
# torch.from_numpy(ndarray) → Tensor
a = np.arange(12).reshape(3,4) #numpy只能通过reshape来实现多维数组
y = torch.from_numpy(a)
# 利用这个方法创建的 tensor 和原来的 ndarray 共享内存，当修改其中一个数据，另外一个也会被改动。[可以直接通过切片来修改数据]
y[2,0] = 9
print(y)
print(a)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 9,  9, 10, 11]])
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 9  9 10 11]]


## 根据数值创建Tensor

In [ ]:
# torch.zeros()
# torch.zeros(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
        # size: 张量的形状
        # out: 输出的张量，如果指定了 out，那么torch.zeros()返回的张量和 out 指向的是同一个地址
        # layout: 内存中布局形式，有 strided，sparse_coo 等。当是稀疏矩阵时，设置为 sparse_coo 可以减少内存占用。
        # device: 所在设备，cuda/cpu
        # requires_grad: 是否需要梯度
""" 
同理还有 torch.ones()，torch.ones_like() 
"""
# torch.zeros_like
# torch.zeros_like(input, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)
        # 功能：根据 input 形状创建全 0 张量
        # input: 创建与 input 同形状的全 0 张量
        # dtype: 数据类型
        # layout: 内存中布局形式，有 strided，sparse_coo 等。当是稀疏矩阵时，设置为 sparse_coo 可以减少内存占用。


In [4]:

out_t = torch.tensor([1,4,5])
t = torch.zeros((3, 3), out=out_t) #此时的out_t已经被覆盖成t
# 指定out应该是将新建的zero张量写入到out张量中，不指定out则新建一个张量。然后无论如何，返回表示这个新的全0矩阵的张量
print(t, '\n', out_t)
# id 是取内存地址。最终 t 和 out_t 是同一个内存地址
print(id(t), id(out_t), id(t) == id(out_t))


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
140561611294720 140561611294720 True


In [ ]:
# torch.full()
# torch.full(size, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
        # 功能：创建自定义数值的张量
        # size: 张量的形状，如(3, 3)
        # fill_value: 张量中每一个元素的值
# torch.full_like()和torch.zeros_like相同

In [5]:
t = torch.full((3, 3), 1)
print(t)
# 这种只能创建数据相同的张量

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [ ]:
# torch.arange()
# torch.arange(start=0, end, step=1, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
# 创建等差的一维张量
        # 功能：创建等差的 1 维张量。注意区间为[start, end)。
        # start: 数列起始值
        # end: 数列结束值，开区间，取不到结束值
        # step: 数列公差，默认为 1

In [6]:
t = torch.arange(2, 10, 2)
print(t)


tensor([2, 4, 6, 8])


In [ ]:
# torch.linspace()
# torch.linspace(start, end, steps=100, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
        # 功能：创建均分的 1 维张量。数值区间为[start, end]
        # start: 数列起始值
        # end: 数列结束值
        # steps: 数列长度(元素个数)

In [7]:
t = torch.linspace(2, 10, 6)
print(t)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])


## 根据概率创建 Tensor

In [8]:
# torch.normal()
# torch.normal(mean, std, *, generator=None, out=None)
        # 功能：生成正态分布(高斯分布) 
                # 数据可能是围绕着一个中心分布，不偏左、不偏右、也不或高或低，呈现一种中间高、两边低的趋势，我们称之为“正态分布”：
        # mean: 均值
        # std: 标准差
# 共有四种方式

### 1、mean 为标量，std 为标量。这时需要设置 size。

In [3]:
# mean：标量 std: 标量
# 这里需要设置 size   size: _size, *
t_normal = torch.normal(0, 1, size=(4,))
print(t_normal)

tensor([ 0.4286,  1.4078, -0.8289,  0.3476])


### 2、mean 为标量，std 为张量

In [24]:
# mean：标量 std: 张量
mean = 2
std = torch.arange(1, 5, dtype=torch.float)
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}".format(mean, std))
print(t_normal)


mean:2
std:tensor([1., 2., 3., 4.])
tensor([ 3.2278,  3.2841,  3.7933, -0.5807])


### 3、mean 为张量，std 为标量

In [40]:
# mean：张量 std: 标量
mean = torch.arange(1, 5, dtype=torch.float)
std = 1
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}".format(mean, std))
print(t_normal)

mean:tensor([1., 2., 3., 4.])
std:1
tensor([-1.2212,  2.4317,  3.1891,  3.4174])


### 4、mean 为张量，std 为张量

In [25]:
# mean：张量 std: 张量
mean = torch.arange(1, 5, dtype=torch.float)
std = torch.arange(1, 5, dtype=torch.float)
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}".format(mean, std))
print(t_normal)

mean:tensor([1., 2., 3., 4.])
std:tensor([1., 2., 3., 4.])
tensor([0.3530, 0.3780, 4.7195, 4.9932])


In [ ]:
# torch.randn() 和 torch.randn_like()
# torch.randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
        # 功能：生成标准正态分布。
        # size: 张量的形状


In [29]:
x = torch.randn(3,4)
x

tensor([[-1.2673,  1.7223,  0.0696,  0.1807],
        [ 1.7121, -0.0554, -0.0431,  0.8940],
        [-1.5080, -0.9476,  0.0425,  0.1670]])

In [ ]:
# torch.rand() 和 torch.rand_like()
# torch.rand(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
        # 功能：在区间 [0, 1) 上生成均匀分布。

In [30]:
x = torch.rand(3, 4)
x


tensor([[0.4748, 0.4836, 0.7356, 0.9461],
        [0.1866, 0.1128, 0.6700, 0.1265],
        [0.9056, 0.1615, 0.9719, 0.8020]])

In [ ]:
# torch.randint() 和 torch.randint_like()
# randint(low=0, high, size, *, generator=None, out=None,dtype=None, layout=torch.strided, device=None, requires_grad=False)
        # 功能：在区间[low, high) 上生成整数均匀分布。
        # size: 张量的形状

In [33]:
x = torch.randint(0,5,size=(4,))
x

tensor([0, 4, 4, 0])