In [1]:
import torch
import numpy as np

# 初始化一个全零矩阵

In [12]:
out = torch.ones(5,3)
out

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
x = torch.zeros((5,3),out=out)
out

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
out_t = torch.tensor([4,5])
out_t


tensor([4, 5])

In [4]:
out_t = torch.tensor([4,5])
# 这里制定了 out
t = torch.zeros((3, 3), out=out_t)
print(t, '\n', out_t)
# id 是取内存地址。最终 t 和 out_t 是同一个内存地址
print(id(t), id(out_t), id(t) == id(out_t))


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
140284500194752 140284500194752 True


# 直接传入数据

In [4]:
x = torch.Tensor([5,5,3])
x
# 注意Tensor是一个矩阵类型的，所以在传输数据时要以矩阵格式传输

tensor([5., 5., 3.])

In [6]:
x = x.new_ones(5,3,dtype=torch.torch.double)
x = torch.randn_like(x,dtype=torch.torch.float)
x
# randn_like 作用是仿照上一个张量创建一个一模一样的张量

tensor([[ 0.8406,  0.8390,  0.6747],
        [-0.8709, -0.1998,  0.9777],
        [-0.0808,  0.7951, -0.4749],
        [-0.9025,  1.2334, -1.8280],
        [-0.7204, -1.7774, -2.6636]])

In [7]:
x.size()

torch.Size([5, 3])

In [9]:
x.shape

torch.Size([5, 3])

# 基本计算方法

In [11]:
print(x)
y = torch.rand(5,3)
print("x+y是：",x+y)

tensor([[ 0.8406,  0.8390,  0.6747],
        [-0.8709, -0.1998,  0.9777],
        [-0.0808,  0.7951, -0.4749],
        [-0.9025,  1.2334, -1.8280],
        [-0.7204, -1.7774, -2.6636]])
x+y是： tensor([[ 1.6758,  1.4263,  1.2411],
        [-0.8372,  0.1287,  1.8863],
        [-0.0661,  1.6777, -0.4448],
        [-0.6448,  1.3051, -1.4787],
        [-0.0276, -1.0502, -2.0218]])


# 索引

In [14]:
print(x)
x[:,1]
# 取所有行的第一列

tensor([[ 0.8406,  0.8390,  0.6747],
        [-0.8709, -0.1998,  0.9777],
        [-0.0808,  0.7951, -0.4749],
        [-0.9025,  1.2334, -1.8280],
        [-0.7204, -1.7774, -2.6636]])


tensor([ 0.8390, -0.1998,  0.7951,  1.2334, -1.7774])

# view 可以改变矩阵的维度

In [15]:
x = torch.randn(4,4)
print(x.size())
y = x.view(16)
print(y.size())
z = x.view(-1,8)
# -1的作用是根据后一个维度自动计算前一个维度
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


## 与numpy进行协同操作

In [17]:
a = torch.ones(5)
b = a.numpy()
b
# .numpy的作用是将张量转换成numpy格式

array([1., 1., 1., 1., 1.], dtype=float32)

In [19]:
a = np.ones(5)
b = torch.from_numpy(a)
b
# torch.from_numpy是将numpy格式转换成Tensor格式

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

## 标量 scalar

In [17]:
import torch
from torch import tensor
a = tensor(42)
a.dim()
a.item()
b = a * 2
b.item()
# 此时的a就是一个标量，可以进行运算，也可以当做一个值


84

## 向量 vector

In [20]:
v = tensor([1.5,2.0,3.6])
v.dim()
v.size()

torch.Size([3])

## 矩阵 Matrix

In [38]:
# 矩阵通常是多维，在深度学习中常用与计算
s = tensor([[1,2.],[3, 4]],dtype=float)
s.dim()
print(s)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [39]:
s.matmul(s)
s

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [42]:
print(s)
tensor([2,5],dtype=float).matmul(s)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


tensor([17., 24.], dtype=torch.float64)