In [2]:
import torch
import numpy as np

# 需要求导的，可以手动定义

In [3]:
# 方法一
x = torch.randn(3,4,requires_grad=True)
x

tensor([[ 1.7937,  1.4139,  0.9823,  0.3730],
        [ 0.4127,  0.1978, -0.1563,  0.8962],
        [-0.2656,  1.7248,  1.4722, -0.4702]], requires_grad=True)

In [4]:
# 方法二：
x = torch.randn(3,4)
x.requires_grad = True
x

tensor([[-1.6555, -1.1397,  0.0185,  0.3001],
        [ 1.3669, -0.6259,  0.5115,  0.7090],
        [-1.7477, -0.4370,  1.4087, -1.3764]], requires_grad=True)

In [5]:
b = torch.randn(3,4,requires_grad=True)
print(b)
t = x+b
print(t)
y = t.sum()
y

tensor([[-0.1344, -1.4319, -1.0915,  0.3131],
        [ 0.8314,  2.1347,  0.1515, -0.9744],
        [ 2.4599, -0.8820,  0.7951, -0.6868]], requires_grad=True)
tensor([[-1.7900, -2.5716, -1.0730,  0.6132],
        [ 2.1983,  1.5088,  0.6631, -0.2655],
        [ 0.7122, -1.3190,  2.2037, -2.0632]], grad_fn=<AddBackward0>)


tensor(-1.1829, grad_fn=<SumBackward0>)

In [8]:
# 进行反向传播
y.backward()
print(y)

tensor(-1.1829, grad_fn=<SumBackward0>)


In [7]:
print(b.grad)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
